//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorReglas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispositivos()
        {
            this.PropiedadDispositivo = new HashSet<PropiedadDispositivo>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Certeza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropiedadDispositivo> PropiedadDispositivo { get; set; }
    }
}
