//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorReglas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reglas
    {
        public int Id { get; set; }
        public string TipoEvaluacion { get; set; }
        public string PropiedadEvaluacion { get; set; }
        public string ValorPropiedadEvaluacion { get; set; }
        public string PropiedadDispositivo { get; set; }
        public string ValorPropiedadDispositivo { get; set; }
        public int Certeza { get; set; }
    }
}
